### PR TITLE
Debug memory leak on keep-alive connections

### PR DESCRIPTION
**Pull request by yaa110**

### CODE REVIEW

**Comment by milani** [comment]
Did you test the fix? Does it solve issue in https://github.com/luvit/luvit too?

**Comment by yaa110** [comment]
tested and worked fine. Which issue in luvit do you mean?

**Comment by milani** [comment]
This issue persists in luvit too, so if it is fixed here, you can also send a PR for luvit project.

**Comment by yaa110** [comment]
it was fixed in luvit ([PR#958](https://github.com/luvit/luvit/pull/958)), too.

**Pull request merged**
